### ISSUE TITLE
Migration to Angular 2.0

### ISSUE THREAD

**Issue by yanivefraim** [mgechev/angularjs-style-guide#121] opened 2015-05-10 18:58 UTC
What about adding style guidelines that are focused on preparing for Angular 2.0. 

I saw this [amazing](https://youtu.be/MC3DfMEBaKQ) video from ngVegas and read this [cool article](https://www.airpair.com/angularjs/posts/component-based-angularjs-directives), which let me think that we should really focus on preparing our apps so it will be much simpler to migrate to Angular 2 when the time comes.

What do you think? Is there a place for a section like this in the guide?

**Comment by mgechev** [comment] 2015-05-12 11:45
I think it makes sense but somehow I don't see it fit in the current document.

Lets collect a few more opinions and add the section if there are more people, who think that we need it! :-)

**Comment by agnislav** [comment] 2015-05-12 16:31
I'm for the offer. As Angular2 is one of most discussed topics, any guides on "How to write on Angular1 to be prepared for migration to Angular2" will be totally useful.

**Comment by roanbester** [comment] 2015-05-13 12:08
A lot of the magic with migration is sticking to best practices in angularjs 1.x. Use modular code, separation of concerns etc. With angular 1.x, if you make use of services as intended, have thin controllers and componentized directives you're already halfway there.

So, I would keep the angularjs 1.x doc separate, as-is (as it probably already has the best practices stuff in) and create a separate one focusing just on the 2.0 angular stuff.

Check out this [site](http://gurustop.net/newsletter/10), especially the section

### Getting your Angular 1.3/1.4 App Ready for Angular 2

* Write code as ES6 classes, everything (directives, services, etc.)
* Use the new Angular router (luckily it’s just around the corner)
* Use directives more than controllers
* Use the controllerAs syntax in your directives instead of using $scope

**Comment by mgechev** [comment] 2015-05-13 16:45
[Here is one more opinion](https://twitter.com/mgechev/status/598239099502362625) on the topic.

**Comment by mgechev** [comment] 2015-05-14 09:36
I'm thinking about slight refactoring of the repo.

1. Move all translations to `i18n` directory
2. Add separate markdown file with development practices for easier migration process

**Comment by mgechev** [comment] 2015-07-20 07:43
On AngularU John Papa announced that he's working with the core team on a migration guide. We can close this issue.

**Closed by mgechev** 2015-07-20 07:43 UTC
Labels: enhancement
